version: "3.8"

services:
  server:
    container_name: Marsh_backend
    build : .
    env_file: .env
    command: gunicorn marsh_project.wsgi:application --bind 0.0.0.0:8000 --reload
#    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    container_name: database
    image: mysql
    env_file: database_config/mysql.env
    command: --init-file /data/application/init.sql
    ports:
      - "3308:3306"
    volumes:
      - db_volume:/var/lib/mysql
      - ./database_config/init.sql:/data/application/init.sql

volumes:
  db_volume:
  static_volume:
  media_volume: